/**
 * data.js 생성 모듈
 * 수집·변환된 식당 데이터를 restaurant-finder/js/data.js 형식으로 출력한다.
 */

const fs = require('fs');
const path = require('path');

const BASE_POINT = { lat: 37.5796, lng: 126.9770, name: '한국생산성본부' };

const FILTER_META = `const FILTER_META = {
  flavor:   { label: '맛',          icon: '👅',
    options: ['매운', '단', '짠', '기름진', '담백 깔끔', '새콤한', '감칠맛'] },
  texture:  { label: '식감·무게감', icon: '🫦',
    options: ['바삭한', '쫄깃한', '아삭한', '부드러운', '헤비한', '가벼운'] },
  cooking:  { label: '조리 방식',   icon: '🍳',
    options: ['구이·볶음', '국물·찜', '생식·무침', '튀김', '면류·파스타', '오븐·화덕', '발효·숙성'] },
  cuisine:  { label: '음식 국적',   icon: '🌍',
    options: ['한식', '중식', '일식', '양식', '아시안', '퓨전'] },
  temp:     { label: '온도',        icon: '🌡️',
    options: ['차가운', '뜨끈한'] },
  occasion: { label: '상황·목적',   icon: '🎯',
    options: ['혼밥', '사교·회식', '안주'] },
  health:   { label: '건강·소화',   icon: '💪',
    options: ['디톡스', '벌크업·보양', '저자극'] },
};`;

function generateDataJs(restaurants) {
  const entries = restaurants.map((r, i) => {
    const obj = {
      id: i + 1,
      name: r.name,
      address: r.address,
      lat: r.lat,
      lng: r.lng,
      distanceKm: r.distanceKm,
      mainMenu: r.mainMenu,
      priceRange: r.priceRange,
      openHours: r.openHours,
      tags: r.tags,
      tip: r.tip,
    };
    return '  ' + JSON.stringify(obj, null, 2).split('\n').join('\n  ');
  });

  const content = `// Auto-generated by collect-restaurants.js
// Generated at: ${new Date().toISOString()}
// Total restaurants: ${restaurants.length}

const BASE_POINT = ${JSON.stringify(BASE_POINT)};

${FILTER_META}

const RESTAURANTS = [
${entries.join(',\n')}
];
`;

  const outPath = path.resolve(__dirname, '..', 'js', 'data.js');
  fs.writeFileSync(outPath, content, 'utf-8');
  console.log(`✅ data.js 생성 완료: ${restaurants.length}개 식당 → ${outPath}`);
  return outPath;
}

module.exports = { generateDataJs, BASE_POINT };
