/**
 * data.js 생성 모듈
 * 수집·변환된 식당 데이터를 restaurant-finder/js/data.js 형식으로 출력한다.
 */

const fs = require('fs');
const path = require('path');

const BASE_POINT = { lat: 37.574919, lng: 126.973518, name: '한국생산성본부' };

const FILTER_META = `const FILTER_META = {
  flavor:   { label: '맛, 식감',    icon: '👅',
    options: ['매운', '단', '짠', '기름진', '담백 깔끔', '새콤한', '감칠맛',
              '바삭한', '쫄깃한', '아삭한', '부드러운', '헤비한', '가벼운'] },
  cooking:  { label: '조리 방식',   icon: '🍳',
    options: ['구이·볶음', '국물·찜', '생식·무침', '튀김', '면류·파스타',
              '오븐·화덕', '발효·숙성', '전·부침', '조림·수비드', '샐러드·회',
              '밥·죽', '베이킹', '기타'] },
  cuisine:  { label: '음식 국적',   icon: '🌍',
    options: ['한식', '중식', '일식', '양식', '이탈리안', '동남아', '기타지역', '퓨전'] },
  foodType: { label: '음식 종류',   icon: '🍜',
    options: ['국밥·탕·찌개', '냉면·국수', '구이', '족발·보쌈', '백반·가정식',
              '분식', '치킨', '중식', '마라·훠궈', '일식·초밥', '라멘·우동',
              '돈카츠', '피자·파스타', '스테이크·양식', '햄버거', '브런치·샐러드',
              '카페·디저트', '베트남·동남아', '인도·커리', '멕시코·남미', '퓨전',
              '죽·가벼운식사'] },
  occasion: { label: '상황·목적',   icon: '🎯',
    options: ['혼밥', '사교', '단체', '비즈니스'] },
  distance: { label: '거리',        icon: '📍',
    options: ['500m이내', '1km이내', '1.5km이내'] },
  price:    { label: '가격',        icon: '💰',
    options: ['1만원이하(₩)', '1~2만원(₩₩)', '2~3만원(₩₩₩)', '3만원 이상(₩₩₩₩)'] },
};`;

// 이름+주소 기반 안정 해시 ID (data.js 재생성 시에도 ID 유지)
function stableId(name, address) {
  const str = (name || '') + '|' + (address || '');
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) + hash + str.charCodeAt(i)) & 0x7fffffff;
  }
  return hash;
}

function generateDataJs(restaurants) {
  const usedIds = new Set();
  const entries = restaurants.map((r, i) => {
    let id = stableId(r.name, r.address);
    // 해시 충돌 방지
    while (usedIds.has(id)) id++;
    usedIds.add(id);
    const obj = {
      id,
      name: r.name,
      address: r.address,
      lat: r.lat,
      lng: r.lng,
      distanceKm: r.distanceKm,
      mainMenu: r.mainMenu,
      priceRange: r.priceRange,
      openHours: r.openHours,
      tags: r.tags,
      tip: r.tip,
    };
    return '  ' + JSON.stringify(obj, null, 2).split('\n').join('\n  ');
  });

  const content = `// Auto-generated by collect-restaurants.js
// Generated at: ${new Date().toISOString()}
// Total restaurants: ${restaurants.length}

const BASE_POINT = ${JSON.stringify(BASE_POINT)};

${FILTER_META}

const RESTAURANTS = [
${entries.join(',\n')}
];
`;

  const outPath = path.resolve(__dirname, '..', 'js', 'data.js');
  fs.writeFileSync(outPath, content, 'utf-8');
  console.log(`✅ data.js 생성 완료: ${restaurants.length}개 식당 → ${outPath}`);
  return outPath;
}

module.exports = { generateDataJs, BASE_POINT };
